### PR TITLE
(RE-12065)(RE-12069) Remove s390x for sles and el

### PR DESCRIPTION
**Pull request by sarameisburger**
update spec tests accordingly - I swapped s390x for i386 in the tests, if that's a bad idea I can change it or just remove it altogether

Please add all notable changes to the "Unreleased" section of the CHANGELOG.

### CODE REVIEW

**Comment by e-gris** [comment]
Did we just leave off i386 before because it would be over-testing?
If that's the case, it seems fine to me to replace s390x with i386.

**Comment by underscorgan** [comment]
@sarameisburger are any projecs/pipelines still building for s390x? If so we should get the platform removed there before it's removed from packaging since that will break shipping.

**Comment by sarameisburger** [comment]
@underscorgan From what I can tell there aren't any? But I don't know how to extensively check. PE and Puppet Agent have EOL'd it and I'm not seeing it in recent builds of other projects like puppetserver and puppetdb

**Comment by underscorgan** [comment]
I just did a quick scan in ci-job-configs and I'm not seeing anything, so 👍

**Pull request merged**
