### PR TITLE
(PA-5043) Remove Red Hat 7 (aarch64) from the packaging repository

### PR DESCRIPTION
**Pull request by skyamgarp**

### CODE REVIEW

**Review by mhashizume — APPROVED** [review]
LGTM! It would be helpful, but not necessary, to add this change to CHANGELOG.md in the "Unreleased" section under a heading titled "Removed"

**Comment by e-gris** [comment]
We do require the CHANGELOG update for platform additions/deletions.

**Comment by mhashizume** [comment]
Ah, gotcha. I saw that there wasn't anything added for https://github.com/puppetlabs/packaging/pull/1216 so I wasn't sure i that was just an oversight.

**Review by e-gris — APPROVED** [review]

**Comment by e-gris** [comment]
It was an oversight.

**Pull request merged**
