### PR TITLE
(RE-5392) Ship ezbake.manifest if it exists

### PR DESCRIPTION
**Pull request by melissa**

### CODE REVIEW

**Comment by melissa** [comment]
built http://jenkins-release.delivery.puppetlabs.net/job/puppetserver-packaging-2017-02-27-23-10-53-2.7.2.master.SNAPSHOT.2017.02.27T2310/ which produced http://builds.puppetlabs.lan/puppetserver/2.7.2.master.SNAPSHOT.2017.02.27T2310/artifacts/

also built http://jenkins-release.delivery.puppetlabs.net/job/puppet-packaging-2017-02-27-23-19-13-8f9c35bd3fc97edfcb77fc442eddc6c5579423cf/ which produced http://builds.puppetlabs.lan/puppet/8f9c35bd3fc97edfcb77fc442eddc6c5579423cf/artifacts/

**Comment by melissa** [comment]
Okie, I've added in a commit to rename ezbake.manifest to product stuff

http://builds.puppetlabs.lan/puppetserver/2.7.2.master.SNAPSHOT.2017.02.27T2325/artifacts/

**Comment by melissa** [comment]
Hmm, it looks like converting this file to yaml is going to require changes in ezbake rather than in packaging. I've updated this PR to handle that future addition

**Comment by shrug** [comment]
Do we want it converted to yaml?

**Comment by melissa** [comment]
We'd need to convert it in order for kerminator to parse it

**Comment by shrug** [comment]
How does kerminator parse the ezbake stuff now?

**Comment by melissa** [comment]
I don't think it does... but I'm not super sure. @stahnma ?

**Comment by shrug** [comment]
https://github.com/puppetlabs/kerminator/blob/master/files/scripts/ezbake.js

**Comment by melissa** [comment]
right, that. That's yaml, it's just pulling from the yaml file we already populate and drop in the artifacts directory. That doesn't include a comprehensive dependency tree, which is what we want here.

```
:description: Puppet Server (clojure 1.8.0,puppetserver 2.7.2-master-SNAPSHOT,trapperkeeper-webserver-jetty9
  1.7.0)
```

**Comment by shrug** [comment]
oh, hah yeah sorry apparently I can't read.

**Comment by shrug** [comment]
👍 pending travis

**Comment by melissa** [comment]
I opened https://tickets.puppetlabs.com/browse/EZ-107 to handle the ezbake part of this

**Pull request merged**
