### PR TITLE
(maint) Capture output from remote ssh command

### PR DESCRIPTION
**Pull request by underscorgan**

### CODE REVIEW

**Comment by sarameisburger** [comment]
👍

**Comment by melissa** [comment]
👍  will merge once tests are green

**Comment by melissa** [comment]
Wow, travis is taking forever this morning :( I might just merge this....

**Comment by melissa** [comment]
wait, no, I can't even push the button if tests aren't green. This sucks

**Comment by underscorgan** [comment]
:( :( :(

**Comment by mckern** [comment]
WHAT ARE TESTS DOOOOING

**Comment by underscorgan** [comment]
my build was cancelled??? 😡

**Comment by melissa** [comment]
travis--

**Comment by mckern** [comment]
I tried to cancel it to rekick it and the UI won't let me 😢

**Comment by mckern** [comment]
Ah, there we go. It finally gave me the "retry" button.

**Comment by mckern** [comment]
I mangled the Branch Protection to allow admin override. This is merged.
3323_12__wrecking_bar_tekton_4-1

**Pull request merged**
