### PR TITLE
Revert "Revert "(maint) Separate signing module by package format""

### PR DESCRIPTION
**Pull request by mwaggett**
This reverts commit 9745e3fc7a5c9791aaed3a531a897417eb26dfaf.

Revert "Revert "(maint) Update nightly tasks to use new signing function""

This reverts commit 68316e5f0ef6c4c92675ecc91ea7fa4cbe83f884.

### CODE REVIEW

**Comment by mwaggett** [comment]
Tested here: https://jenkins-master-prod-1.delivery.puppetlabs.net/job/platform_nightly-repo_packaging_ship/3375/

**Comment by underscorgan** [comment]
@mwaggett linked job isn't using this branch.

```
10:51:27 Using packaging 0.4.3.1082.g795fe2f from git://github.com/mwaggett/packaging.git (at maint/1.0.x/sad@795fe2f)
```

**Comment by mwaggett** [comment]
@underscorgan I know, but I swear I tested with these changes. I wanted to continue working on that other branch while I pushed this stuff up.

**Comment by underscorgan** [comment]
OK. I was just verifying that you tested what you thought you tested, since it looked wrong.

**Pull request merged**
