### PR TITLE
(RE-9948) generate_repo_configs tag creates repo config for aix

### PR DESCRIPTION
**Pull request by mwaggett**
This commit excludes aix rpms when generating repo configs.

### CODE REVIEW

**Comment by mwaggett** [comment]
Built without AIX repo configs: http://builds.delivery.puppetlabs.net/puppet-agent/6dd7ca6fd41628a147ecc51541cf732a0df1a082/

**Comment by melissa** [comment]
I'm seeing the repo_configs for aix in the yaml file you linked

```
:platform_data:
  aix-6.1-power:
    :artifact: "./aix/6.1/PC1/ppc/puppet-agent-5.3.3.406.g6dd7ca6-1.aix6.1.ppc.rpm"
    :repo_config: "../repo_configs/rpm/pl-puppet-agent-6dd7ca6fd41628a147ecc51541cf732a0df1a082-aix-6.1-ppc.repo"
  aix-7.1-power:
    :artifact: "./aix/7.1/PC1/ppc/puppet-agent-5.3.3.406.g6dd7ca6-1.aix7.1.ppc.rpm"
    :repo_config: "../repo_configs/rpm/pl-puppet-agent-6dd7ca6fd41628a147ecc51541cf732a0df1a082-aix-7.1-ppc.repo"
  el-7-x86_64:
    :artifact: "./el/7/PC1/x86_64/puppet-agent-5.3.3.406.g6dd7ca6-1.el7.x86_64.rpm"
    :repo_config: "../repo_configs/rpm/pl-puppet-agent-6dd7ca6fd41628a147ecc51541cf732a0df1a082-el-7-x86_64.repo"
```

**Comment by mwaggett** [comment]
@melissa I know, I made the commit to change that after I built, but didn't want to rebuild.

**Comment by mwaggett** [comment]
The 1.0.x version is building right now and that should have all the things in it / not in it.

**Comment by melissa** [comment]
Is there a way to generate these files without shipping them? That would make it so you wouldn't have to sit through a whole build to test it.

**Comment by mwaggett** [comment]
@melissa yeah, on it.

**Comment by mwaggett** [comment]
no repo configs for AIX:
```
:platform_data:
  aix-6.1-power:
    :artifact: "./aix/6.1/PC1/ppc/puppet-agent-5.3.3.406.g6dd7ca6-1.aix6.1.ppc.rpm"
    :repo_config:
  aix-7.1-power:
    :artifact: "./aix/7.1/PC1/ppc/puppet-agent-5.3.3.406.g6dd7ca6-1.aix7.1.ppc.rpm"
    :repo_config:
  el-7-x86_64:
    :artifact: "./el/7/PC1/x86_64/puppet-agent-5.3.3.406.g6dd7ca6-1.el7.x86_64.rpm"
    :repo_config: "../repo_configs/rpm/pl-puppet-agent-6dd7ca6fd41628a147ecc51541cf732a0df1a082-el-7-x86_64.repo"
```

**Comment by mwaggett** [comment]
@melissa I have a test in the 1.0.x version, which is almost ready for review.

**Pull request merged**
