### PR TITLE
RE-11145 Update Changelog for 0.99.10

### PR DESCRIPTION
**Pull request by e-gris**

### CODE REVIEW

**Comment by mwaggett** [comment]
I would do a merge-up from master once that PR goes in, so that the 0.6.8 changelog gets included in this.

**Comment by mwaggett** [comment]
also, is that Distelli check new?? am I crazy?? wherever it came from, it needs to use a later ruby..

**Comment by e-gris** [comment]
"Merge-up from master" -- not sure what this means exactly. Do you mean merging master to 1.0.x before merging this PR?

**Comment by mwaggett** [comment]
@e-gris yes

**Pull request merged**
