### PR TITLE
Remove all the labs, also questions

### PR DESCRIPTION
**Pull request by sbeaulie**

### CODE REVIEW

**Comment by sbeaulie** [comment]
Does it also support setting `MOCK` as an environment variable instead of passing it in the rake command line?
See https://github.com/sbeaulie/packaging/blame/master/README.md#L89

**Comment by sbeaulie** [comment]
trivial change

**Comment by stahnma** [comment]
So, I kind of think we should s/labs/inc since otherwise it's really difficult to figure out when we're talking about puppet, the software vs puppet the company.

**Comment by shrug** [comment]
I think I agree with @stahnma, +1 to 'inc'

**Comment by sbeaulie** [comment]
@stahnma and @shrug this PR was more about asking my question above than removing the labs. My understanding is that Github has this limitation where you cannot link a line number for a `.md` file, so I created a PR I could blame-link above. I read the docs, still unsure how I can use that MOCK variable, see my first comment above please ^^

**Comment by stahnma** [comment]
Should we rebase this and update it or just close it out?

**Pull request merged**
