### PR TITLE
(maint) Add note about master->stable targets in ci-job-configs

### PR DESCRIPTION
**Pull request by branan**

### CODE REVIEW

**Comment by kylog** [comment]
:+1:

**Comment by stahnma** [comment]
@branan rebase and then we can merge.

**Comment by stahnma** [comment]
@branan rebase and we can merge.

**Comment by branan** [comment]
@stahnma rebased

**Comment by branan** [comment]
with no conflicts? Why did I need to rebase at all? github--

**Comment by branan** [comment]
Oh, because branch protection, and the test run is "out of date" if I'm not up-to-date with master. That's... a bit aggressive

**Comment by branan** [comment]
@stahnma this should be ready to merge now

**Comment by stahnma** [comment]
Obsoleted by #513

**Pull request closed without merging**
