### PR TITLE
(maint) Add task to ship learning VMs

### PR DESCRIPTION
**Pull request by underscorgan**

### CODE REVIEW

**Comment by underscorgan** [comment]
Hoping this task combined with http://jenkins-compose.delivery.puppetlabs.net/job/(DO%20NOT%20USE)%20Testing%20LearningVM%20ship/ will allow for self-serve learning vm shipping

**Comment by underscorgan** [comment]
Testing this now at http://jenkins-compose.delivery.puppetlabs.net/job/(DO%20NOT%20USE)%20Testing%20LearningVM%20ship/5.

**Comment by underscorgan** [comment]
This successfully shipped the learning vm!

**Comment by stahnma** [comment]
👍  @mckern @melissa have a look.

**Pull request merged**
