### PR TITLE
(maint) Assign additional PA release tickets to the project manager role

### PR DESCRIPTION
**Pull request by whopper**

### CODE REVIEW

**Comment by shrug** [comment]
needs a rebase

**Comment by shrug** [comment]
:+1:  otherwise

**Comment by stahnma** [comment]
@whopper I tried to merge manually and push, but apparently since we have hooks setup on this repo, I can't just do that :(

**Comment by whopper** [comment]
@stahnma rebased! If my other PR gets merged first I might have to rebase again.

**Pull request merged**
