### PR TITLE
(maint) enable timestamper plugin on autogenerated builds

### PR DESCRIPTION
**Pull request by underscorgan**

### CODE REVIEW

**Comment by underscorgan** [comment]
Look at those timestamps go! http://jenkins-release.delivery.puppetlabs.net/job/puppetserver-packaging-2017-01-17-10-27-31-2.7.2.master.SNAPSHOT.2017.01.17T1027/command=pl_deb%20COW=base-jessie-i386.cow/1/console

**Comment by shrug** [comment]
oh nice, 👍

**Comment by haus** [comment]
@underscorgan worth adding to the downstream template as well?

**Comment by underscorgan** [comment]
@haus for downstream I have less confidence that they'll have the same plugin available? that's my only concern. I know the other two are going to run on jenkins-release.

**Comment by haus** [comment]
@underscorgan i just meant the downstream job (template) that happens on j-r

**Comment by underscorgan** [comment]
@haus ah, makes sense. Added.

**Comment by haus** [comment]
@underscorgan added but not pushed?

**Comment by underscorgan** [comment]
@haus hm, pushed. i think github was just being slow.

**Comment by underscorgan** [comment]
@haus now it's really there

**Comment by haus** [comment]
:100:

**Pull request merged**
