### PR TITLE
(maint) Remove EOL platforms

### PR DESCRIPTION
**Pull request by mwaggett**

### CODE REVIEW

**Comment by melissa** [comment]
Have all of these platforms been fully removed from all the other build/test pipelines? If not, then this will cause pipelines failures.

**Comment by mwaggett** [comment]
@melissa They weren't built for agent 5.3.2, so I assume so?

@McdonaldSeanp @ScottGarman Can you confirm?

**Comment by shrug** [comment]
ping @geoffnichols

**Comment by McdonaldSeanp** [comment]
@shrug @melissa @mwaggett These OSes are no longer built and/or tested anywhere.

These defs can be removed.

**Pull request merged**
