### PR TITLE
(maint) Update ticketmatch reconciliation step

### PR DESCRIPTION
**Pull request by joshcooper**
Previously, the `tickets` task generated two subtasks for reconciling
jira tickets and git commits.

This commit consolidates the subtasks into one, and updates the
description to use the ticketmatch script that Thomas wrote.

Also updated example usage to use Nick's jira account.

### CODE REVIEW

**Comment by joshcooper** [comment]
I haven't been able to test this, because apparently ruby-jira is not compatible with our jira instance. It also failed for @melissa and @MikaelSmith which could be a sign of bigger problems with ticket creation in general.

**Comment by haus** [comment]
:+1: would love to test it someday

**Comment by joshcooper** [comment]
I rebased to pick up the change to not use the `re` user and it is working as expected:

```
0 ~/work/puppet (stable)  $ bundle exec rake pl:tickets BUILDER=josh DEVELOPER=josh WRITER=josh RELEASE=9.9.9 PROJECT=PUP DATE=2015/07/15 JIRA_USER=josh
Logging in to https://tickets.puppetlabs.com as josh
Password please:
Okay trying to log in to https://tickets.puppetlabs.com as josh ...
Creating tickets based on:
{:builder=>"josh",
 :developer=>"josh",
 :writer=>"josh",
 :release=>"9.9.9",
 :project=>"PUP",
 :date=>"2015/07/15",
 :site=>"https://tickets.puppetlabs.com",
 :username=>"josh"}
Main release ticket: PUP-4868 (josh) - puppet 9.9.9 2015/07/15 Release
	Subticket  1: PUP-4869 (josh) - Is the code ready for release?
	Subticket  2: PUP-4870 (josh) - Reconcile git commits and JIRA tickets
	Subticket  3: PUP-4871 (josh) - Update version number in source
	Subticket  4: PUP-4872 (josh) - Merge master into stable
	Subticket  5: PUP-4873 (josh) - Is the Jira tidy-up done for this release and prepared for the next one?
	Subticket  6: PUP-4874 (josh) - Prepare long form release notes and short form release story
	Subticket  7: PUP-4875 (josh) - Tag the release and create packages
	Subticket  8: PUP-4876 (josh) - Smoke test packages
	Subticket  9: PUP-4877 (josh) - Go/no-go meeting (before 4pm)
	Subticket 10: PUP-4878 (josh) - Push tag
	Subticket 11: PUP-4879 (josh) - Packages pushed
	Subticket 12: PUP-4880 (josh) - Docs pushed
	Subticket 13: PUP-4881 (eric.sorenson) - Send out announcements
	Subticket 14: PUP-4882 (josh) - Close all resolved tickets in Jira
```

**Comment by joshcooper** [comment]
ping @haus @melissa

**Comment by haus** [comment]
i'm :+1:

**Comment by joshcooper** [comment]
It looks like the recent puppet release ticket for 4.2.2 (https://tickets.puppetlabs.com/browse/PUP-5157) doesn't have this change. Do we have to tag a new version of `packaging` for this change to take effect? Or do we need to update puppet to use a newer version?

**Comment by melissa** [comment]
It would only have picked up the new changes if the user ran `rake package:implode package` bootstrap prior to running the task

**Pull request merged**
