### PR TITLE
(RE-14142) Refactor dmg signing.

### PR DESCRIPTION
**Pull request by e-gris**
Primarily: fix bug that was quietly ignoring signing dmgs that weren't
in the 'apple' directory. Add 'mac' and 'osx' as considerations.

Also, do a good bit of refactoring for clarity to throw errors when
things are amiss.

The Dir.glob is still a big problem that I did not address. The signer
should be told explicitly what to sign rather than have to infer it
from the directory structure.

Please add all notable changes to the "Unreleased" section of the CHANGELOG.

### CODE REVIEW

**Comment by e-gris** [comment]
@beechtom / @lucywyman Mostly FYI. 

I'll plan on shipping this early next week.

**Review by underscorgan — APPROVED** [review]
LGTM! just to confirm, it looks like the big behavioral change here is checking apple, mac, and osx directories for dmgs instead of just looking in apple? Everything else looked more like cleanup/refactoring

**Comment by e-gris** [comment]
Correct. 

Sub problem-1 as I perceived it was that it was capable of passing true when it found nothing. I fixed that.

Sub problem-2 was that I found the code hard to read. I hope the cleanup helped that.

**Comment by beechtom** [comment]
@e-gris Thanks for getting this fixed! Is a release planned for today or sometime later this week?

**Comment by e-gris** [comment]
@beechtom Working on the release right now.

**Comment by beechtom** [comment]
@e-gris Awesome! :D Thanks!

**Pull request merged**
