### PR TITLE
(MAINT) Wouldn't it be rad to view Pkg::Config in a readable format?

### PR DESCRIPTION
**Pull request by mckern**
I thought it would be, so in service of some of my other work I bashed two rocks together to make this. It'll add two rake tasks to make validating/viewing the current state of a project's config easier.

giphy 2

### CODE REVIEW

**Comment by underscorgan** [comment]
:100:

**Comment by mckern** [comment]
Rebased against `HEAD`

**Comment by mckern** [comment]
Force pushed to restart the Travis cycle.

**Pull request merged**
