### PR TITLE
(RE-2542) shipping staging automation for osx

### PR DESCRIPTION
**Pull request by heathseals**
This commit updates the automation to allow shipping of dmgs for vanagon projects ( vanagon_project set to true ) and when build_dmg is not set. It also updates the source directory for the rsync to be pkg/apple/ instead of pkg/apple/*.dmg.  This adds support for apple projects that have a repo defined, such as PC1.

### CODE REVIEW

**Comment by stahnma** [comment]
:+1:

**Comment by haus** [comment]
@heathseals what happens if you uber_ship or ship_dmgs when there are none?

**Comment by heathseals** [comment]
@haus just tested and nothing appears to happen if there are no dmgs ( no failures, but also no indication that the apple pkg directory was empty ).  does it need to be verbose?

**Comment by haus** [comment]
@heathseals verbose would be cool. mostly i wanted to make sure that if we need to ship puppet-agent 1.2.0 without osx packages that the ship wouldn't explode.

**Comment by heathseals** [comment]
@haus updated.

**Pull request merged**
